services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"

  # redis:
  #   image: redis:7-alpine
  #   container_name: lyricslive-redis
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--save", "", "--appendonly", "no"]
