name: 'LyricsLive deployment pipeline'

on: 
  push:
    branches:
      - main

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: install frontend dependencies
        working-directory: ./frontend
        run: npm install
      
    